name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: install node
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: pull emscripten-zbar-sdk
        run: docker pull maslick/emscripten-zbar-sdk
      - name: build QR wasm
        run: docker run -e INPUT_FILE=zbar/qr.cpp -e OUTPUT_FILE=qr -v $(pwd):/app maslick/emscripten-zbar-sdk make
      - name: build BAR wasm
        run: docker run -e INPUT_FILE=zbar/barcode.cpp -e OUTPUT_FILE=barcode -v $(pwd):/app maslick/emscripten-zbar-sdk make
      - name: install npm dependencies
        run: yarn install --frozen-lockfile
      - name: build React bundle
        run: npm run build
      - name: push to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
           Success!
           A ${{ github.event_name }} event triggered the pipeline.
           Ref: ${{ github.ref }}
           Commit hash: ${{ github.sha }}
           See https://github.com/maslick/koder-react/actions for more details
      - name: job failed
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Oops! Build failed
            See https://github.com/maslick/koder-react/actions for more details
